channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - ipykernel

  # Standard Python Data Science stack:
  - scipy
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn

  # Mass spec:
  - ppx
  - pyteomics
  - spectrum_utils
  #- percolator     # linux only :P
  - biopython

  # local:
  - pip:
      - git+https://github.com/TalusBio/vizta # plot theming.
      - -e .
